# Generated by Django 5.0 on 2023-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
